name: ty

on:
  push:
  pull_request:

jobs:
  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
        with:
          enable-cache: true
      - run: uv run --locked ty check --output-format=github
